todo:
 base-url: /api
 post-url: /tasks
 get-url: /tasks
 put-url: /tasks/{id}
 delete-url: /tasks/{id}
user:
 base-url: /api
 post-url: /register
 validation-url: /login
 sign-out-url: /signOut
log:
 base-url: /api
 get-url: /logs

