todo:
 base-url: /task
 post-url: /newTask
 get-url: /getTasks
 put-url: /updateTask/{id}
 delete-url: /deleteTask/{id}
user:
 base-url: /user
 post-url: /newUser
 validation-url: /validateUser
log:
 base-url: /log
 get-url: /getLogs

